# Generated by Django 5.1 on 2024-08-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='main', max_length=255, verbose_name='menu_name')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.menuitem', verbose_name='Parent')),
            ],
        ),
    ]
